### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by dchud** [mitre/GrowthViz#5]
Can we remove `master` and `refactor`?

**Comment by eedrummer** [comment]
`master` can definitely go.

`refactor` was my start to break up `charts.py` and add some testing. We don't have to take the specific approach in there, but it would be nice to do something like this.

**Comment by dchud** [comment]
Thanks @eedrummer - I'll remove `master`.

Maybe we can discuss `refactor` on one of our upcoming Tuesday calls? Would be good to capture goals in a ticket. @andersonmeredithk and I can take a look at what you've done so far in the meantime.

**Comment by dchud** [comment]
`master` deleted, closing.
