### ISSUE TITLE
Update Python code to match PEP8

### ISSUE THREAD

**Issue by dchud** [mitre/GrowthViz#6]
Sorry to be *that* guy... but I guess I just am. :)

It would be great to update `charts.py` to match the [PEP8 specs](https://pep8.org/). This would most obviously affect tab (in spaces) width, line length, and spacing between functions, among other things. It's generally preferred, and fairly easy to do, and my main worry is that at some point I might touch this code and my editor will automatically do it anyway.

The simplest approach might be to use a formatter like [black](https://black.readthedocs.io/en/stable/). It would take the guessing and argument out of it, which is usually a bonus. If you're using an editor like VSCode, it's fairly straightforward to integrate so that it [auto-formats Python files on save using black](https://dev.to/adamlombard/how-to-use-the-black-python-code-formatter-in-vscode-3lo0).

Happy to discuss/argue, but hopefully this isn't too controversial!

**Comment by eedrummer** [comment]
I love this idea. As a python newbie, I wasn't aware of black, but I've used similar tools (checkstyle for java, RuboCop for ruby and gofmt for go).

Not in love with the 4 space indent, but would rather conform to community standards.

**Comment by dchud** [comment]
Thanks for being open to a conflicting-with-your-experience/preference style! I'll follow up w/@andersonmeredithk regarding timing/priority.

RuboCop is a terrific name.
